# Generated by Django 2.1.3 on 2018-11-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_book_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(default='Coding', max_length=255),
        ),
    ]
